 ***
 ***                    By : AliHam Dev
 ***
 ***      this Program UnHide All Folders in Current Directory
 ***
 ***      –h: It clears the Hidden file attribute to show hidden files.
 ***      –r: It clears the Read-only file attribute to allow you modify the file after it shows.
 ***      –s: It clears the System file attribute.
 ***      /s: It applies attrib and any command-line options to matching files in the current directory and all of its subdirectories.
 ***      /d: It applies attrib and any command-line options to directories.
 ***
 attrib -h -r -s /s /d
